/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopnavbarIndexRouteImport } from './routes/topnavbar/index'
import { Route as ShoppingcartIndexRouteImport } from './routes/shoppingcart/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as ThankyouTransactionIdRouteImport } from './routes/thankyou/$transactionId'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as CheckoutTransactionIdRouteImport } from './routes/checkout/$transactionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopnavbarIndexRoute = TopnavbarIndexRouteImport.update({
  id: '/topnavbar/',
  path: '/topnavbar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingcartIndexRoute = ShoppingcartIndexRouteImport.update({
  id: '/shoppingcart/',
  path: '/shoppingcart/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankyouTransactionIdRoute = ThankyouTransactionIdRouteImport.update({
  id: '/thankyou/$transactionId',
  path: '/thankyou/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTransactionIdRoute = CheckoutTransactionIdRouteImport.update({
  id: '/checkout/$transactionId',
  path: '/checkout/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/$transactionId': typeof CheckoutTransactionIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/thankyou/$transactionId': typeof ThankyouTransactionIdRoute
  '/error': typeof ErrorIndexRoute
  '/login': typeof LoginIndexRoute
  '/shoppingcart': typeof ShoppingcartIndexRoute
  '/topnavbar': typeof TopnavbarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/$transactionId': typeof CheckoutTransactionIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/thankyou/$transactionId': typeof ThankyouTransactionIdRoute
  '/error': typeof ErrorIndexRoute
  '/login': typeof LoginIndexRoute
  '/shoppingcart': typeof ShoppingcartIndexRoute
  '/topnavbar': typeof TopnavbarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/$transactionId': typeof CheckoutTransactionIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/thankyou/$transactionId': typeof ThankyouTransactionIdRoute
  '/error/': typeof ErrorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/shoppingcart/': typeof ShoppingcartIndexRoute
  '/topnavbar/': typeof TopnavbarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout/$transactionId'
    | '/product/$productId'
    | '/thankyou/$transactionId'
    | '/error'
    | '/login'
    | '/shoppingcart'
    | '/topnavbar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout/$transactionId'
    | '/product/$productId'
    | '/thankyou/$transactionId'
    | '/error'
    | '/login'
    | '/shoppingcart'
    | '/topnavbar'
  id:
    | '__root__'
    | '/'
    | '/checkout/$transactionId'
    | '/product/$productId'
    | '/thankyou/$transactionId'
    | '/error/'
    | '/login/'
    | '/shoppingcart/'
    | '/topnavbar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutTransactionIdRoute: typeof CheckoutTransactionIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ThankyouTransactionIdRoute: typeof ThankyouTransactionIdRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ShoppingcartIndexRoute: typeof ShoppingcartIndexRoute
  TopnavbarIndexRoute: typeof TopnavbarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topnavbar/': {
      id: '/topnavbar/'
      path: '/topnavbar'
      fullPath: '/topnavbar'
      preLoaderRoute: typeof TopnavbarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoppingcart/': {
      id: '/shoppingcart/'
      path: '/shoppingcart'
      fullPath: '/shoppingcart'
      preLoaderRoute: typeof ShoppingcartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thankyou/$transactionId': {
      id: '/thankyou/$transactionId'
      path: '/thankyou/$transactionId'
      fullPath: '/thankyou/$transactionId'
      preLoaderRoute: typeof ThankyouTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$transactionId': {
      id: '/checkout/$transactionId'
      path: '/checkout/$transactionId'
      fullPath: '/checkout/$transactionId'
      preLoaderRoute: typeof CheckoutTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutTransactionIdRoute: CheckoutTransactionIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ThankyouTransactionIdRoute: ThankyouTransactionIdRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ShoppingcartIndexRoute: ShoppingcartIndexRoute,
  TopnavbarIndexRoute: TopnavbarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
